basic:
  name: "server"
  port: 8086

users:
  client: { token: "token" }

components:
  # - name: server/vless-port
  #   type: websocket
  #   port: 443
  #   path: /donghuicheng
  #   pass: server/vless

  - name: server/vless-in
    type: tcp
    port: 6566
    pass: server/vless

  - name: server/vless-dispatch
    type: vless
    passes:
      tcp: server/debug
      udp: server/udp
    users:
      - id: donghuicheng

  - name: server/debug
    type: channel
    pass: server/vlesstcp
    # show: true

  - name: server/vlesstcp
    type: tcp


  

