basic:
  name: "client"

servers:
  - name: server
    url: "http://client:token@localhost:8086"
    
components:
  - name: server/http
    type: https
    port: 443
    sites: 
      www.test.com:
        cert: "cert"
        key: "key"
        locations:
          /mesh:
            pass: client/channel
        
      "*.mr-tutu.com":
        pass:

  - name: server/http
    type: http
    connect: 8080
    sites: 
      www.test.com:
        pass: client/channel

  - name: client/channel
    type: channel
    show: true    
    pass: server/hub 

  - name: client/tcp
    type: tcp
    pass: 192.168.31.1:80

  - name: client/http
    type: web
    options: 
      target: fsdfasdf

  - name: client/vless
    type: vless



    
      





