basic:
  name: "client"

servers:
  - name: server
    url: "http://client:token@localhost:8086"
    
components:
  - name: client/tcp
    type: tcp
    port: 1080
    pass: client/socks5

  - name: client/socks5
    type: socks5
    passes:
      tcp: client/free
    users: 
      - id: xxxxxxx

  - name: client/free
    type: tcp
      
  # - name: server/http
  #   type: https
  #   port: 443
  #   sites: 
  #     www.test.com:
  #       cert: "cert"
  #       key: "key"
  #       locations:
  #         /mesh:
  #           pass: client/channel
        
  #     "*.mr-tutu.com":
  #       pass:

  # - name: server/http
  #   type: http
  #   connect: 8080
  #   sites: 
  #     www.test.com:
  #       pass: client/channel

  # - name: client/channel
  #   type: channel
  #   show: true    
  #   pass: server/hub 

  # - name: client/tcp
  #   type: tcp
  #   pass: 192.168.31.1:80

  # - name: client/http
  #   type: web
  #   options: 
  #     target: fsdfasdf

  # - name: client/vless
  #   type: vless



    
      





